#!/bin/bash

sm2 --start THIRD_PARTY_APPLICATION API_DEFINITION API_SUBSCRIPTION_FIELDS THIRD_PARTY_DEVELOPER PUSH_PULL_NOTIFICATIONS_API INTERNAL_AUTH --appendArgs '{"INTERNAL_AUTH": ["-Dapplication.router=testOnlyDoNotUseInAppConf.Routes"]}'

./run_local.sh
